LIST_HEADERS = ["Изображение", "Название", "Тип"]
LIST_HEADERS_MAIN = ["Изо", "Название"]
WIDTH_HEADERS = [75, 25]
WIDTH_HEADERS
SHOWING_LIST_IMAGE_SIZE = 150
MAIN_SHOWING_IMAGE_SIZE = 50
LOAD_SCREEN_SIZE = [480, 330]
LOAD_IMAGE_SIZE = [250, 250]
NEW_TYPE = "Новый тип"